# Generated by Django 3.1.3 on 2020-12-09 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='bestellung',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kunde'),
        ),
    ]